import { config } from 'dotenv';
config({ path: '.env.local' });

import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { randomUUID } from 'crypto';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const img = (seed: string) => `https://picsum.photos/seed/${seed}/800/600`;
const imgs = (seed: string) => JSON.stringify([img(seed), img(`${seed}-b`), img(`${seed}-c`)]);
const tags = (t: string[]) => JSON.stringify(t);

const USERS = [
  {
    email: 'sophie@oddfolk-seed.test', name: 'Sophie Marchetti', username: 'sophiem',
    bio: 'Event stylist based in Shoreditch with a warehouse full of beautiful furniture for hire. Specialising in rustic and industrial-chic aesthetics.',
    location: { name: 'Shoreditch Studio', address: '14 Curtain Road', postcode: 'EC2A 3AT', city: 'London', lat: 51.5247, lng: -0.0788 },
    listings: [
      { title: 'Trestle Dining Table (8ft)', category: 'Event furniture', tags: tags(['trestle','dining table','rustic','wooden','8ft']), condition: 'Good', color: 'Natural', quantity: 3, price1Day: 45, price3Day: 110, price7Day: 220, description: 'Classic 8ft trestle dining table, perfect for weddings and supper clubs. Seats 8–10 guests comfortably. Clean, sanded pine finish. Available individually or as a set. Pairs beautifully with cross-back or bench seating.' },
      { title: 'Cross-Back Folding Chairs (Set of 10)', category: 'Event furniture', tags: tags(['cross-back','chairs','folding','wooden','wedding']), condition: 'Good', color: 'Natural', quantity: 2, price1Day: 30, price3Day: 75, price7Day: 150, description: 'Ten beautifully crafted cross-back folding chairs. A wedding and garden party staple. Light enough to move easily, sturdy enough to last the whole day. Seat pad hire available separately.' },
      { title: 'Vintage Bar Cart (brass & glass)', category: 'Event furniture', tags: tags(['bar cart','brass','vintage','drinks trolley']), condition: 'Good', color: 'Gold', quantity: 1, price1Day: 35, price3Day: 85, price7Day: 160, description: 'Elegant vintage-style bar cart with brass frame and two glass shelves. Perfect as a cocktail station or drinks display. Holds bottles, glasses and garnish trays beautifully.' },
      { title: 'Rustic Wooden Step Ladder', category: 'Props & décor', tags: tags(['ladder','rustic','wooden','display','décor']), condition: 'Good', color: 'Natural', quantity: 2, price1Day: 15, price3Day: 38, price7Day: 75, description: 'Repurposed wooden step ladder used as a beautiful tiered display stand. Works wonderfully for welcome drinks, card displays or flower arrangements at the aisle.' },
      { title: 'Rattan Peacock Chair', category: 'Event furniture', tags: tags(['rattan','peacock chair','boho','chair','vintage']), condition: 'Like New', color: 'Natural', quantity: 2, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Iconic statement rattan peacock chair — the ultimate photo moment piece. Ideal as a sweetheart seat, throne chair or lounge corner focal point.' },
      { title: 'Whitewashed Bench Set (2 × 6ft)', category: 'Event furniture', tags: tags(['bench','whitewashed','white','wooden','seating']), condition: 'Good', color: 'White', quantity: 3, price1Day: 20, price3Day: 50, price7Day: 95, description: 'Pair of solid wood 6ft benches with a whitewashed finish. Aisle seating, dining or cocktail hour perches. Versatile and lightweight. Delivered as a pair.' },
      { title: 'Copper Spool Side Table', category: 'Event furniture', tags: tags(['copper','spool','side table','industrial','drinks table']), condition: 'Good', color: 'Copper', quantity: 4, price1Day: 20, price3Day: 48, price7Day: 90, description: 'Industrial copper-finished cable spool repurposed as a side or drinks table. Great grouped in clusters for cocktail receptions or as bar-height perch tables.' },
      { title: 'Emerald Velvet Chaise Longue', category: 'Soft furnishings', tags: tags(['chaise','velvet','emerald','green','lounge']), condition: 'Like New', color: 'Green', quantity: 1, price1Day: 55, price3Day: 135, price7Day: 270, description: 'Stunning deep emerald velvet chaise longue — a total show-stopper for any event lounge area or photoshoot. Solid hardwood frame, deep-cushioned seat. A true investment piece.' },
      { title: 'Farmhouse Dining Table (10ft)', category: 'Event furniture', tags: tags(['farmhouse','dining table','10ft','rustic','large']), condition: 'Good', color: 'Natural', quantity: 2, price1Day: 65, price3Day: 160, price7Day: 320, description: 'Solid oak-effect 10ft farmhouse dining table. Seats 12–14 guests. The hero piece for any reception room. Heavy but we can assist with logistics for local deliveries.' },
      { title: 'Ghost Chairs (Set of 6)', category: 'Event furniture', tags: tags(['ghost chair','acrylic','transparent','modern','wedding']), condition: 'Like New', color: 'Neutral', quantity: 2, price1Day: 40, price3Day: 95, price7Day: 190, description: 'Six sleek acrylic ghost chairs — a contemporary classic that works with any colour palette. Stackable and lightweight. Perfect for sweetheart tables or lounge corners.' },
    ],
  },
  {
    email: 'marcus@oddfolk-seed.test', name: 'Marcus Webb', username: 'marcusw',
    bio: 'Lighting designer and prop collector in Hackney. I rent out everything from festoon strings to neon signs for events across East London.',
    location: { name: 'Hackney Warehouse', address: '27 Mare Street', postcode: 'E8 3RH', city: 'London', lat: 51.5450, lng: -0.0553 },
    listings: [
      { title: 'Edison Festoon String Lights (20m)', category: 'Lighting', tags: tags(['festoon','string lights','edison','outdoor','20m']), condition: 'Good', color: 'Neutral', quantity: 5, price1Day: 35, price3Day: 85, price7Day: 170, description: 'Twenty metres of warm-white Edison bulb festoon lights on a black cable. Plug-and-play with standard 13A socket. Suitable for indoor and covered outdoor use. Hooks and cable ties included.' },
      { title: 'Copper Pillar Lanterns (Set of 6)', category: 'Lighting', tags: tags(['lanterns','copper','pillar','candle','centrepiece']), condition: 'Good', color: 'Copper', quantity: 3, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Set of 6 mixed-height copper pillar lanterns. Stunning clustered together on a table or lining an aisle. Use with real pillar candles or flameless LED candles (available on request).' },
      { title: 'Geometric Brass Pendant Lamp', category: 'Lighting', tags: tags(['pendant','geometric','brass','ceiling light','industrial']), condition: 'Like New', color: 'Gold', quantity: 4, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Open-frame geometric brass pendant lamp. E27 fitting — takes standard bulbs or Edison-style filament bulbs. Adds instant industrial-luxe warmth to marquees, barns or warehouse venues.' },
      { title: 'Paper Globe Lanterns (Set of 12)', category: 'Lighting', tags: tags(['paper lanterns','globe','hanging','ceiling','colourful']), condition: 'Good', color: 'White', quantity: 3, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Twelve white paper globe lanterns in mixed sizes (20cm, 30cm, 40cm). Hang from ceilings for an instant airy, whimsical feel. Battery-powered LED lights included.' },
      { title: 'Brass Candlestick Cluster (Set of 9)', category: 'Lighting', tags: tags(['candlesticks','brass','cluster','taper candles','centrepiece']), condition: 'Good', color: 'Gold', quantity: 4, price1Day: 25, price3Day: 60, price7Day: 118, description: 'Nine brass candlestick holders in assorted heights — tall, medium and short. Group together for lush candlelit tableaux. Taper candles available separately. Looks incredible in low light.' },
      { title: "LED Neon 'Love' Sign (60cm)", category: 'Lighting', tags: tags(['neon','LED','love sign','wedding','wall art']), condition: 'Like New', color: 'Pink', quantity: 2, price1Day: 40, price3Day: 95, price7Day: 190, description: "Warm white LED neon 'Love' sign, 60cm wide. USB powered with a 3m lead. Perfect backdrop piece for wedding photos or party tables. Mounts on a stand or hangs on a wall hook." },
      { title: 'Fairy Light Curtain (3m × 3m)', category: 'Lighting', tags: tags(['fairy lights','curtain','backdrop','twinkle','string lights']), condition: 'Good', color: 'White', quantity: 4, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Warm white fairy light curtain measuring 3m wide by 3m tall. 300 micro-LEDs on fine silver wire. Drapes behind top tables, arches or stage backdrops. Mains powered with 5m lead.' },
      { title: 'Battery Uplighters (Set of 4)', category: 'Lighting', tags: tags(['uplighters','LED','battery','colour changing','wireless']), condition: 'Like New', color: 'Neutral', quantity: 3, price1Day: 45, price3Day: 110, price7Day: 220, description: 'Set of 4 wireless LED uplighters with RGBW colour mixing. App or remote controlled. 10+ hour battery life per charge. Transform any venue wall or column instantly. No cables, no fuss.' },
      { title: 'Vintage Arc Floor Lamp', category: 'Lighting', tags: tags(['floor lamp','arc','vintage','lounge','ambient']), condition: 'Good', color: 'Gold', quantity: 2, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Mid-century arc floor lamp with a brushed brass finish and cream fabric shade. Adds instant lounge-area warmth to any event. Ideal for photobooth corners or chill-out zones.' },
      { title: 'Silver Candelabra Set (×3, 5ft)', category: 'Lighting', tags: tags(['candelabra','silver','tall','centrepiece','gothic']), condition: 'Good', color: 'Silver', quantity: 2, price1Day: 35, price3Day: 85, price7Day: 170, description: 'Three towering 5ft silver candelabras. Dramatic centrepieces for top tables, altars or entrance halls. Holds 5 taper candles each. Candles included.' },
    ],
  },
  {
    email: 'isla@oddfolk-seed.test', name: 'Isla Fernandez', username: 'islaf',
    bio: 'Passionate about beautiful table settings. I collect vintage crockery, glassware and cutlery for hire at weddings, supper clubs and pop-ups across North London.',
    location: { name: 'Islington Flat', address: '8 Upper Street', postcode: 'N1 0PQ', city: 'London', lat: 51.5362, lng: -0.1026 },
    listings: [
      { title: 'Mismatched Vintage Crockery Set (50 pieces)', category: 'Tableware', tags: tags(['crockery','vintage','mismatched','plates','tableware']), condition: 'Good', color: 'Mixed', quantity: 1, price1Day: 50, price3Day: 120, price7Day: 240, description: 'Fifty pieces of curated mismatched vintage crockery — dinner plates, side plates and bowls in assorted florals, pastels and geometric patterns. Perfect for eclectic wedding breakfasts and supper clubs.' },
      { title: 'Copper Charger Plates (Set of 20)', category: 'Tableware', tags: tags(['charger plates','copper','metallic','table setting','wedding']), condition: 'Like New', color: 'Copper', quantity: 2, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Twenty hammered copper charger plates, 33cm diameter. Elevate any table setting instantly. Food-safe lacquer finish. Wipe clean. Ideal for weddings, corporate dinners and photo shoots.' },
      { title: 'Rose Gold Cutlery Set (for 20)', category: 'Tableware', tags: tags(['cutlery','rose gold','stainless steel','flatware','wedding']), condition: 'Like New', color: 'Rose Gold', quantity: 2, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Full rose gold stainless steel cutlery set for 20 guests — starter fork, dinner fork, dinner knife, dessert spoon and teaspoon. Presented in a roll bag. Dishwasher safe.' },
      { title: 'Crystal Champagne Flutes (Set of 24)', category: 'Tableware', tags: tags(['champagne flutes','crystal','glasses','wedding','toast']), condition: 'Good', color: 'Neutral', quantity: 2, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Twenty-four crystal-clear champagne flutes. Classic tulip shape, 180ml capacity. Perfect for toasts, prosecco reception drinks or dessert table styling. Carefully packed in a padded crate.' },
      { title: 'Gin Balloon Glasses (Set of 20)', category: 'Tableware', tags: tags(['gin glasses','balloon','copa','glasses','bar']), condition: 'Like New', color: 'Neutral', quantity: 2, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Twenty large bowl Copa de Balon gin glasses. Perfect for elaborate gin and tonic stations. 580ml capacity, dishwasher safe. Great for cocktail receptions and garden parties.' },
      { title: 'Terracotta Sharing Bowls (Set of 12)', category: 'Tableware', tags: tags(['terracotta','bowls','sharing','rustic','ceramics']), condition: 'Like New', color: 'Neutral', quantity: 2, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Twelve hand-thrown terracotta-glazed sharing bowls in two sizes. Beautiful for mezze-style wedding breakfasts, supper clubs or food-forward events. Each bowl is unique.' },
      { title: 'Marble & Slate Cheeseboard Set', category: 'Tableware', tags: tags(['cheeseboard','marble','slate','serving','catering']), condition: 'Like New', color: 'Neutral', quantity: 3, price1Day: 15, price3Day: 38, price7Day: 75, description: 'Large marble slab and two slate boards with cheese knives and small ceramic condiment pots. Perfect for grazing table displays or wedding canapé stations.' },
      { title: 'Tiered Cake Stand Set (3 sizes)', category: 'Tableware', tags: tags(['cake stand','tiered','white','display','dessert table']), condition: 'Good', color: 'White', quantity: 3, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Set of three white ceramic tiered cake stands in small (20cm), medium (28cm) and large (35cm). Perfect for wedding cakes, dessert tables or afternoon tea.' },
      { title: 'Linen Napkin Roll Set (30 napkins)', category: 'Tableware', tags: tags(['napkins','linen','white','ivory','table linen']), condition: 'Like New', color: 'White', quantity: 3, price1Day: 18, price3Day: 44, price7Day: 88, description: 'Thirty crisp white or ivory linen napkins, 45cm square. Pre-rolled and banded. Iron-flat on arrival. Perfect for weddings, supper clubs and private dining.' },
      { title: 'Vintage Teapot & Cup Set (service for 12)', category: 'Tableware', tags: tags(['teapot','cups','vintage','afternoon tea','china']), condition: 'Good', color: 'Mixed', quantity: 1, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Vintage English china tea service for 12 — teapot, sugar bowl, milk jug and twelve cups and saucers in mismatched floral patterns. Perfect for vintage-themed parties and afternoon teas.' },
    ],
  },
  {
    email: 'theo@oddfolk-seed.test', name: 'Theo Okafor', username: 'theoo',
    bio: 'Creative director and prop collector in Brixton. I source unique statement pieces that make events unforgettable.',
    location: { name: 'Brixton Storage', address: '3 Atlantic Road', postcode: 'SW9 8HX', city: 'London', lat: 51.4613, lng: -0.1133 },
    listings: [
      { title: 'Hexagonal Floral Arch Frame (8ft)', category: 'Props & décor', tags: tags(['arch','floral','hexagonal','wedding','backdrop']), condition: 'Good', color: 'Gold', quantity: 1, price1Day: 40, price3Day: 95, price7Day: 190, description: 'Powder-coated gold hexagonal arch frame, 8ft tall. Perfect base for florals, greenery, drapery or fabric installations. Freestanding with a weighted base. The ultimate ceremony backdrop.' },
      { title: 'Copper Welcome Sign Stand', category: 'Props & décor', tags: tags(['sign stand','copper','welcome sign','easel','wedding']), condition: 'Like New', color: 'Copper', quantity: 2, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Adjustable copper-pipe welcome sign stand. Holds boards up to A0 size. Pairs with your own foam board or perspex sign. A sleek, modern alternative to a wooden easel.' },
      { title: "Neon 'And They Lived…' Sign (100cm)", category: 'Lighting', tags: tags(['neon','sign','wedding','and they lived','LED']), condition: 'Like New', color: 'White', quantity: 1, price1Day: 55, price3Day: 135, price7Day: 270, description: "Warm white LED neon 'And They Lived...' sign, 100cm wide. A viral wedding favourite. USB powered, comes with a 3m cable and mounting hooks. Perfect above a sweetheart table or in a photobooth area." },
      { title: 'Perspex Table Number Frames (Set of 20)', category: 'Signage & displays', tags: tags(['table numbers','perspex','acrylic','wedding','signage']), condition: 'Like New', color: 'Neutral', quantity: 2, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Twenty A5 freestanding perspex table number frames in a modern arch shape. Insert your own printed cards. Clean, minimal and works with any colour palette.' },
      { title: 'Vintage Leather Suitcase Stack (Set of 3)', category: 'Props & décor', tags: tags(['suitcase','vintage','leather','travel','décor']), condition: 'Vintage/Antique', color: 'Brown', quantity: 2, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Three stacked vintage leather suitcases in complementary tan and brown tones. Beautiful as a card collection display, gift table centrepiece or entrance hall decoration.' },
      { title: 'Rustic Wishing Well Box', category: 'Props & décor', tags: tags(['wishing well','cards','gifts','rustic','wooden']), condition: 'Good', color: 'Natural', quantity: 1, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Charming wooden wishing well card box with a padlocked slot top and removable base. Personalised sign holder on the front. Perfect for wedding card and gift collections.' },
      { title: "Giant 'LOVE' Letter Lights (60cm each)", category: 'Lighting', tags: tags(['LOVE','letter lights','giant','wedding','props']), condition: 'Good', color: 'White', quantity: 1, price1Day: 45, price3Day: 110, price7Day: 220, description: "Four 60cm tall marquee-style LOVE letter lights in white. Each letter takes standard G45 bulbs and runs off standard plug sockets. A must-have for wedding dancefloors and entrance halls." },
      { title: 'Selfie Photo Booth Frame (2m × 1.5m)', category: 'Props & décor', tags: tags(['photo booth','frame','selfie','gold','wedding']), condition: 'Good', color: 'Gold', quantity: 1, price1Day: 20, price3Day: 48, price7Day: 95, description: "Gold glitter-effect photo booth frame, 2m × 1.5m. Freestanding and Instagram-ready. Pair with your own props box for an interactive guest activity. Lightweight and easy to assemble." },
      { title: 'Copper Lantern Cluster (Set of 9)', category: 'Props & décor', tags: tags(['lanterns','copper','cluster','centrepiece','floor']), condition: 'Good', color: 'Copper', quantity: 2, price1Day: 35, price3Day: 85, price7Day: 170, description: 'Nine copper-finish lanterns in three sizes — small, medium and large. Arranged in a floor cluster they create stunning entrance or ceremony walkway décor. Use with LED or real pillar candles.' },
      { title: 'Macramé Wall Backdrop (3m × 2m)', category: 'Textiles & linens', tags: tags(['macramé','backdrop','boho','wall hanging','natural']), condition: 'Good', color: 'Natural', quantity: 1, price1Day: 45, price3Day: 110, price7Day: 220, description: 'Large hand-knotted macramé wall backdrop in natural cotton rope. 3m wide by 2m tall. Hangs from a wooden dowel on a freestanding copper stand (included). A stunning boho ceremony centrepiece.' },
    ],
  },
  {
    email: 'clara@oddfolk-seed.test', name: 'Clara Ashby', username: 'claraa',
    bio: 'Urban gardener and plant stylist in Notting Hill. I hire out beautiful plants and botanical arrangements for events, photoshoots and pop-ups.',
    location: { name: 'Notting Hill Home', address: '22 Portobello Road', postcode: 'W11 2DY', city: 'London', lat: 51.5116, lng: -0.2012 },
    listings: [
      { title: 'Established Olive Tree Hire (5ft)', category: 'Plants & florals', tags: tags(['olive tree','plant hire','5ft','mediterranean','event']), condition: 'Like New', color: 'Green', quantity: 2, price1Day: 60, price3Day: 145, price7Day: 290, description: 'Beautiful established olive tree, approx 5ft tall in a terracotta pot. A timeless event statement. Great for entrance halls, ceremony aisles or photoshoot backdrops. Delivery and collection included for local events.' },
      { title: 'Dried Pampas Grass Arrangement (Large)', category: 'Plants & florals', tags: tags(['pampas grass','dried flowers','boho','arrangement','neutral']), condition: 'Like New', color: 'Natural', quantity: 3, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Large dried pampas grass arrangement in a terracotta or rattan vase. Approx 90cm tall. No maintenance required — just place and style. A boho staple that photographs beautifully.' },
      { title: 'Eucalyptus Garland (5m)', category: 'Plants & florals', tags: tags(['eucalyptus','garland','greenery','table runner','wedding']), condition: 'Like New', color: 'Green', quantity: 5, price1Day: 25, price3Day: 60, price7Day: 120, description: '5m artificial eucalyptus garland — lush, realistic and reusable. Drape along dining tables, wrap around arch frames or hang from ceilings. A fraction of the cost of fresh foliage and just as beautiful.' },
      { title: 'Succulent Centrepiece Cluster (Set of 8)', category: 'Plants & florals', tags: tags(['succulents','centrepiece','plants','wedding','table']), condition: 'Like New', color: 'Green', quantity: 3, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Eight small potted succulents in terracotta pots, perfect for scattering along dining tables or windowsills. Low maintenance, water-free for the event day. Guests often ask to take them home!' },
      { title: 'Fiddle Leaf Fig (6ft, potted)', category: 'Plants & florals', tags: tags(['fiddle leaf fig','plant hire','6ft','indoor','statement']), condition: 'Like New', color: 'Green', quantity: 2, price1Day: 45, price3Day: 110, price7Day: 220, description: 'Stunning 6ft fiddle leaf fig in a brushed concrete pot. A showstopping indoor statement plant. Perfect for photo corners, reception entrances or venue styling. Handle with care — leaves can be delicate.' },
      { title: 'Fern Table Runner Set (×3, 3m each)', category: 'Plants & florals', tags: tags(['fern','table runner','greenery','tropical','fresh']), condition: 'Like New', color: 'Green', quantity: 3, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Three 3m artificial fern table runners, lush and realistic. Lay down the centre of dining tables for instant tropical or garden-party vibes. Mix with flowers or candles.' },
      { title: 'Tropical Monstera Leaf Arrangement', category: 'Plants & florals', tags: tags(['monstera','tropical','leaves','arrangement','jungle']), condition: 'Like New', color: 'Green', quantity: 3, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Dramatic tropical arrangement featuring large monstera deliciosa leaves, birds of paradise and palm fronds in a sculptural vase. Approx 80cm tall. Makes a bold botanical statement.' },
      { title: 'Trailing Ivy Garland (10m)', category: 'Plants & florals', tags: tags(['ivy','garland','trailing','greenery','arch']), condition: 'Good', color: 'Green', quantity: 8, price1Day: 30, price3Day: 72, price7Day: 145, description: '10m artificial trailing ivy garland, dense and realistic. Drape over arch frames, wrap around poles or hang from ceilings. The most versatile greenery prop in any event hire collection.' },
      { title: 'Dried Banksia & Protea Arrangement', category: 'Plants & florals', tags: tags(['banksia','protea','dried flowers','bohemian','arrangement']), condition: 'Like New', color: 'Natural', quantity: 2, price1Day: 35, price3Day: 85, price7Day: 170, description: 'Striking dried flower arrangement featuring large banksia heads, proteas, dried palms and pampas. In an oversized rattan vase. Perfect for bohemian or desert-themed weddings and events.' },
      { title: 'Potted Citrus Tree Hire (4ft, lemon)', category: 'Plants & florals', tags: tags(['citrus','lemon tree','plant hire','mediterranean','4ft']), condition: 'Like New', color: 'Green', quantity: 2, price1Day: 50, price3Day: 120, price7Day: 240, description: 'Gorgeous lemon tree, approx 4ft tall with real lemons on the branches. In a terracotta pot. A stunning Mediterranean touch for al fresco dinners, supper clubs and photoshoots.' },
    ],
  },
  {
    email: 'reuben@oddfolk-seed.test', name: 'Reuben Drake', username: 'reubend',
    bio: 'Antique dealer and prop collector in Greenwich. Thirty years of sourcing means I have an extraordinary collection of genuine antiques for event hire.',
    location: { name: 'Greenwich Antiques', address: '15 Greenwich Church Street', postcode: 'SE10 9BJ', city: 'London', lat: 51.4826, lng: 0.0077 },
    listings: [
      { title: 'Victorian Button-Back Chaise Longue', category: 'Vintage & antique', tags: tags(['chaise','victorian','antique','velvet','lounge']), condition: 'Vintage/Antique', color: 'Blue', quantity: 1, price1Day: 65, price3Day: 160, price7Day: 320, description: 'Genuine Victorian button-back chaise longue in deep navy velvet with carved mahogany legs. In wonderful vintage condition. The ultimate statement hire piece for high-end events and editorial shoots.' },
      { title: 'Antique Mahogany Writing Bureau', category: 'Vintage & antique', tags: tags(['writing bureau','antique','mahogany','desk','victorian']), condition: 'Vintage/Antique', color: 'Brown', quantity: 1, price1Day: 55, price3Day: 135, price7Day: 270, description: 'Genuine late Victorian mahogany bureau with fold-out writing surface and internal compartments. A remarkable prop for vintage-themed events, editorial photography or film production.' },
      { title: 'Brass Gramophone (working)', category: 'Vintage & antique', tags: tags(['gramophone','brass','antique','vintage','music']), condition: 'Vintage/Antique', color: 'Gold', quantity: 1, price1Day: 40, price3Day: 95, price7Day: 190, description: 'Fully working vintage brass gramophone with a large fluted horn. Plays standard 78rpm records. An extraordinary centrepiece for art deco or 1920s-themed events. Comes with three period 78s.' },
      { title: 'Vintage Steamer Trunk Set (3 sizes)', category: 'Vintage & antique', tags: tags(['steamer trunk','vintage','leather','suitcase','travel']), condition: 'Vintage/Antique', color: 'Brown', quantity: 2, price1Day: 35, price3Day: 85, price7Day: 170, description: 'Set of three genuine vintage steamer trunks in small, medium and large, with original brass fittings and rivets. Stack for dramatic entrance displays or use as props for travel-themed events.' },
      { title: 'Distressed Leather Club Armchair', category: 'Vintage & antique', tags: tags(['armchair','leather','distressed','club chair','vintage']), condition: 'Vintage/Antique', color: 'Brown', quantity: 2, price1Day: 40, price3Day: 95, price7Day: 190, description: 'Beautiful aged leather club armchair with deep-buttoned back and rolled arms. Develops incredible character over time. The sort of chair that makes guests want to linger all evening.' },
      { title: 'Art Deco Cocktail Cabinet', category: 'Vintage & antique', tags: tags(['cocktail cabinet','art deco','drinks','bar','1930s']), condition: 'Vintage/Antique', color: 'Brown', quantity: 1, price1Day: 70, price3Day: 170, price7Day: 340, description: "Genuine 1930s Art Deco cocktail cabinet in walnut veneer with chrome fittings and original mirrored interior. Opens to reveal a full bar. A conversation piece that transforms any event's drinks area." },
      { title: 'Cast Iron Ornate Plant Stand', category: 'Vintage & antique', tags: tags(['plant stand','cast iron','victorian','ornate','garden']), condition: 'Vintage/Antique', color: 'Black', quantity: 3, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Victorian cast iron plant stand with ornate scrollwork detailing. Approx 90cm tall. Perfect for displaying potted plants, floral arrangements or lanterns at event entrances.' },
      { title: 'Victorian Brass Birdcage (Large)', category: 'Vintage & antique', tags: tags(['birdcage','brass','victorian','antique','décor']), condition: 'Vintage/Antique', color: 'Gold', quantity: 2, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Large ornate Victorian brass birdcage, approx 60cm tall. Fill with fairy lights, flowers or candles. Hangs from a hook or sits on a table. An incredibly romantic wedding centrepiece.' },
      { title: 'Enamel Apothecary Drawer Cabinet', category: 'Vintage & antique', tags: tags(['apothecary','cabinet','enamel','drawers','industrial']), condition: 'Vintage/Antique', color: 'White', quantity: 1, price1Day: 45, price3Day: 110, price7Day: 220, description: 'Genuine early 20th century enamel apothecary-style drawer cabinet with 24 individual labelled drawers. An extraordinary display piece for industrial or vintage-themed events.' },
      { title: 'Industrial Factory Stools (Set of 4)', category: 'Vintage & antique', tags: tags(['factory stool','industrial','vintage','metal','seating']), condition: 'Vintage/Antique', color: 'Black', quantity: 2, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Four genuine vintage factory stools in painted steel with adjustable height screw mechanisms. Industrial character and surprising comfort. Perfect for workshop-themed events or industrial-chic venues.' },
    ],
  },
  {
    email: 'amara@oddfolk-seed.test', name: 'Amara Nwosu', username: 'amaran',
    bio: 'Interior stylist and textile collector in Peckham. I offer the most beautiful soft furnishing hire in South London for events that deserve extraordinary comfort.',
    location: { name: 'Peckham Studio', address: '42 Rye Lane', postcode: 'SE15 5BS', city: 'London', lat: 51.4740, lng: -0.0690 },
    listings: [
      { title: 'Jewel-Toned Velvet Cushions (Set of 12)', category: 'Soft furnishings', tags: tags(['cushions','velvet','jewel tones','colourful','luxury']), condition: 'Like New', color: 'Mixed', quantity: 2, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Twelve luxury velvet cushions in deep jewel tones — emerald, sapphire, ruby, amethyst and gold. Scattered across floor seating, lounge sofas or ceremony blanket areas. Covers are dry-cleaned between every hire.' },
      { title: 'Sheepskin Throws (Set of 4)', category: 'Soft furnishings', tags: tags(['sheepskin','throw','luxury','white','lounge']), condition: 'Like New', color: 'White', quantity: 3, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Four large, genuine sheepskin throws — ivory white and incredibly luxurious. Drape over chairs, benches or hay bales for outdoor events. A touch of glamour for winter weddings and evening gatherings.' },
      { title: 'Blush Silk Table Runners (Set of 6)', category: 'Textiles & linens', tags: tags(['table runner','silk','blush','pink','wedding']), condition: 'Like New', color: 'Pink', quantity: 4, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Six 3m blush silk charmeuse table runners, 30cm wide. A soft shimmer that elevates any table setting. Dry-cleaned and pressed before each hire. Works beautifully with gold or copper tableware.' },
      { title: 'Boho Floor Cushion Set (Set of 8)', category: 'Soft furnishings', tags: tags(['floor cushions','boho','meditation','seating','festival']), condition: 'Good', color: 'Mixed', quantity: 2, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Eight oversized floor cushions in assorted boho textiles — kilim, ikat and mudcloth patterns. 70cm square. Perfect for festival-style seating areas, meditation zones or lounge ceremony aisles.' },
      { title: 'Linen Bolster Pillows (Set of 6)', category: 'Soft furnishings', tags: tags(['bolster','pillows','linen','neutral','bed styling']), condition: 'Like New', color: 'Natural', quantity: 3, price1Day: 18, price3Day: 44, price7Day: 88, description: 'Six natural linen bolster pillows, 70cm long. Crisp, minimal and incredibly photogenic. Perfect for styled beds in photoshoots, lounge areas at weddings or decorative bed hire for events.' },
      { title: 'Faux Fur Throws (Set of 4)', category: 'Soft furnishings', tags: tags(['faux fur','throw','white','luxury','winter']), condition: 'Like New', color: 'White', quantity: 4, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Four large white faux fur throws, 200cm × 150cm. Incredibly plush and photogenic. Perfect for winter events, festive gatherings or as a cosy backdrop layer for photobooth corners.' },
      { title: 'Embroidered Ottoman Pouffes (Set of 3)', category: 'Soft furnishings', tags: tags(['pouffes','ottoman','embroidered','moroccan','seating']), condition: 'Good', color: 'Mixed', quantity: 3, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Three large Moroccan-style embroidered leather and fabric pouffes in jewel tones. 50cm diameter. Great as additional seating, footrests or decorative objects in a lounge area.' },
      { title: 'Chunky Knit Throw Blanket', category: 'Soft furnishings', tags: tags(['chunky knit','blanket','throw','cream','cosy']), condition: 'Like New', color: 'Natural', quantity: 5, price1Day: 18, price3Day: 44, price7Day: 88, description: 'Oversized hand-knitted chunky wool throw in cream. Approx 180cm × 140cm. A cosy, tactile piece for autumn and winter events, photoshoots or outdoor evening settings.' },
      { title: 'Silk Sari Table Overlay (6m, gold)', category: 'Textiles & linens', tags: tags(['sari','overlay','silk','gold','indian']), condition: 'Good', color: 'Gold', quantity: 2, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Six metres of antique gold silk sari fabric, repurposed as a stunning table overlay. Puddles luxuriously on the floor. Perfect for mehndi nights, Asian weddings, or any event seeking drama and opulence.' },
      { title: 'Fringe Hammock Chair (pair)', category: 'Soft furnishings', tags: tags(['hammock','fringe','chair','boho','hanging']), condition: 'Good', color: 'Natural', quantity: 2, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Two natural cotton fringe hanging hammock chairs. Hang from a sturdy beam or our freestanding copper frame (available separately). A relaxed, boho focal point for outdoor and indoor events.' },
    ],
  },
  {
    email: 'felix@oddfolk-seed.test', name: 'Felix Lindqvist', username: 'felixl',
    bio: 'AV technician and events photographer in Dalston. I hire out quality audio-visual equipment for parties, weddings and corporate events.',
    location: { name: 'Dalston Workshop', address: '6 Kingsland High Street', postcode: 'E8 2JP', city: 'London', lat: 51.5461, lng: -0.0748 },
    listings: [
      { title: 'Portable PA System (500W)', category: 'Audio visual', tags: tags(['PA system','speakers','sound system','portable','events']), condition: 'Like New', color: 'Black', quantity: 2, price1Day: 75, price3Day: 185, price7Day: 370, description: '500W portable PA system with two column speakers, subwoofer, mixer and Bluetooth connectivity. Perfect for speeches, background music and live performances up to 150 guests. Setup support available.' },
      { title: 'Wireless Lavalier Mic Set (pair)', category: 'Audio visual', tags: tags(['microphone','lavalier','wireless','speeches','wedding']), condition: 'Like New', color: 'Black', quantity: 3, price1Day: 35, price3Day: 85, price7Day: 170, description: 'Pair of professional wireless lavalier (clip-on) microphones with dual receiver. Ideal for wedding ceremonies, speeches, presentations or live events. 50m range. Spare batteries included.' },
      { title: 'HD Projector & Screen (8ft)', category: 'Audio visual', tags: tags(['projector','screen','HD','presentations','cinema']), condition: 'Like New', color: 'Black', quantity: 2, price1Day: 65, price3Day: 160, price7Day: 320, description: '3500 lumen HD projector with an 8ft pull-up screen and HDMI/USB inputs. Brilliant for wedding slideshows, presentations, outdoor cinema or sport screenings. Setup instructions included.' },
      { title: 'LED DJ Booth Facade', category: 'Audio visual', tags: tags(['DJ booth','LED','facade','lighting','events']), condition: 'Good', color: 'Black', quantity: 1, price1Day: 55, price3Day: 135, price7Day: 270, description: 'Modular LED DJ booth facade with programmable RGB front panels. Creates an incredible visual centrepiece for any dancefloor. Folds flat for transport. Fits most standard DJ setups.' },
      { title: 'Open-Air Photo Booth with Printer', category: 'Audio visual', tags: tags(['photo booth','printer','selfie','open air','events']), condition: 'Like New', color: 'Black', quantity: 1, price1Day: 90, price3Day: 220, price7Day: 440, description: 'Professional open-air photo booth with touchscreen kiosk, ring light, instant dye-sub printer and custom branding options. Includes unlimited prints. Delivery and collection within London included.' },
      { title: 'Sequin Photo Backdrop (2m × 2m, silver)', category: 'Props & décor', tags: tags(['backdrop','sequin','silver','photo booth','shimmer']), condition: 'Good', color: 'Silver', quantity: 3, price1Day: 35, price3Day: 85, price7Day: 170, description: 'Large 2m × 2m reversible sequin backdrop on a telescopic stand. Silver on one side, gold on the other. Shimmering and photogenic. Perfect behind a cake table, DJ booth or photo station.' },
      { title: 'Vintage Turntable & Speakers', category: 'Audio visual', tags: tags(['turntable','vinyl','record player','speakers','vintage']), condition: 'Good', color: 'Brown', quantity: 1, price1Day: 45, price3Day: 110, price7Day: 220, description: 'Working vintage-style Bluetooth turntable with matching bookshelf speakers. Plays vinyl and streams Bluetooth. A beautiful prop and functional music solution for cocktail hours and intimate parties.' },
      { title: 'Acoustic Guitar (prop or play)', category: 'Props & décor', tags: tags(['guitar','acoustic','music','prop','display']), condition: 'Good', color: 'Brown', quantity: 2, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Quality acoustic guitar, playable or purely decorative. Lean against a wall, place in a stand or have a musician play at your event. A stylish musical prop for bohemian-themed gatherings.' },
      { title: 'Karaoke Machine (Touchscreen)', category: 'Audio visual', tags: tags(['karaoke','machine','singing','entertainment','party']), condition: 'Like New', color: 'Black', quantity: 1, price1Day: 55, price3Day: 135, price7Day: 270, description: 'Premium touchscreen karaoke machine with two wireless microphones, built-in screen and access to 40,000+ songs. The ultimate party centrepiece. Bluetooth connectivity and disco lighting included.' },
      { title: 'Professional Ring Light Set (pair)', category: 'Audio visual', tags: tags(['ring light','photography','video','lighting','studio']), condition: 'Like New', color: 'Black', quantity: 3, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Two 18-inch professional ring lights with adjustable stands (up to 2m), phone holders and remote controls. Variable colour temperature 3200K–5600K. Perfect for photoshoots, livestreams and events.' },
    ],
  },
  {
    email: 'niamh@oddfolk-seed.test', name: "Niamh O'Brien", username: 'niamho',
    bio: 'Graphic designer and event planner in Camberwell. I design and hire out beautiful signage and display pieces for weddings and corporate events.',
    location: { name: 'Camberwell Studio', address: '31 Denmark Hill', postcode: 'SE5 8RS', city: 'London', lat: 51.4706, lng: -0.0932 },
    listings: [
      { title: 'Chalkboard A-Frames (Set of 4)', category: 'Signage & displays', tags: tags(['chalkboard','A-frame','signage','rustic','wedding']), condition: 'Good', color: 'Black', quantity: 2, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Four double-sided chalkboard A-frame signs in two sizes (60cm and 90cm). Chalk pens included. Perfect for welcome signs, directions, menus and seating plans.' },
      { title: 'Frosted Acrylic Welcome Sign (A1)', category: 'Signage & displays', tags: tags(['welcome sign','acrylic','frosted','modern','wedding']), condition: 'Like New', color: 'Neutral', quantity: 3, price1Day: 25, price3Day: 60, price7Day: 120, description: 'A1 frosted acrylic welcome sign — a blank canvas for personalisation with chalk pens. Freestanding on a brushed gold easel (included). Modern, minimal and endlessly reusable.' },
      { title: 'Wooden Seating Plan Frame (4ft × 3ft)', category: 'Signage & displays', tags: tags(['seating plan','frame','wooden','wedding','display']), condition: 'Good', color: 'Natural', quantity: 2, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Large 4ft × 3ft natural wood frame for your printed seating plan or menu. Freestanding with an adjustable easel back. Fits standard A0 prints or foam board inserts.' },
      { title: 'LED Lightbox Letter Board', category: 'Signage & displays', tags: tags(['lightbox','LED','letter board','changeable','signage']), condition: 'Like New', color: 'Black', quantity: 2, price1Day: 35, price3Day: 85, price7Day: 170, description: 'A2 LED backlit lightbox with a full set of changeable letter tiles. Warm glow. Ideal for personalised welcome messages, table names, menus or fun photo moments. Comes with 200+ letter tiles.' },
      { title: 'Vintage Frame Gallery Wall (15 frames)', category: 'Signage & displays', tags: tags(['frames','gallery wall','vintage','photos','display']), condition: 'Good', color: 'Gold', quantity: 1, price1Day: 40, price3Day: 95, price7Day: 190, description: 'Fifteen ornate gold-finish vintage-style frames in assorted sizes. Pre-arranged as a gallery wall display. Insert your own photos, prints or menus. Includes wall hooks and hanging hardware.' },
      { title: 'Giant Neon Marquee Letters (A–Z)', category: 'Signage & displays', tags: tags(['marquee letters','neon','giant','light up','signage']), condition: 'Good', color: 'White', quantity: 1, price1Day: 45, price3Day: 110, price7Day: 220, description: 'Set of 26 giant 60cm light-up marquee letters in white, each individually powered. Spell out names, words or messages. Hire individual letters at £8/each per day or take the full alphabet.' },
      { title: 'Preserved Moss Letter Art (Set of 3)', category: 'Props & décor', tags: tags(['moss','letters','botanical','wall art','green']), condition: 'Like New', color: 'Green', quantity: 2, price1Day: 35, price3Day: 85, price7Day: 170, description: 'Three large (40cm) box-frame moss letter pieces — spell initials or a short word. Preserved moss in a crisp white shadow box. A stunning botanical touch for wedding walls or table displays.' },
      { title: 'Gold Wire Card & Gift Box', category: 'Props & décor', tags: tags(['card box','gold','wire','gifts','wedding']), condition: 'Like New', color: 'Gold', quantity: 3, price1Day: 15, price3Day: 38, price7Day: 75, description: 'Elegant gold wire post-box-style card and gift holder, approx 40cm × 30cm. A modern alternative to a wooden post box. Padlocked slot with personalised tag holder.' },
      { title: 'Brass Easel Display Stand (5ft)', category: 'Signage & displays', tags: tags(['easel','brass','display','stand','sign']), condition: 'Good', color: 'Gold', quantity: 4, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Five-foot brass floor easel. Adjustable to hold boards from A2 to A0. Elegant and minimal. The go-to display stand for welcome signs, seating plans and menus.' },
      { title: 'Organic Balloon Arch Frame Kit', category: 'Props & décor', tags: tags(['balloon arch','frame','organic','party','wedding']), condition: 'Good', color: 'Neutral', quantity: 2, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Flexible PVC balloon arch frame, up to 4m long. Bends into any organic shape — freestanding or mounted. Balloons not included but we recommend a colour palette to match your theme.' },
    ],
  },
  {
    email: 'javi@oddfolk-seed.test', name: 'Javi Reyes', username: 'javir',
    bio: 'Textile artist in Bethnal Green specialising in event linen hire. Every piece is laundered and pressed professionally between each hire.',
    location: { name: 'Bethnal Green Workshop', address: '19 Cambridge Heath Road', postcode: 'E2 9PA', city: 'London', lat: 51.5278, lng: -0.0574 },
    listings: [
      { title: 'Cheesecloth Table Drapes (Set of 10)', category: 'Textiles & linens', tags: tags(['cheesecloth','drape','table','boho','wedding']), condition: 'Like New', color: 'White', quantity: 3, price1Day: 35, price3Day: 85, price7Day: 170, description: 'Ten 3m lengths of ivory cheesecloth table draping. The defining boho wedding textile of the decade. Drapes beautifully over tables, arches and overhead frames. Pre-washed for a relaxed, organic look.' },
      { title: 'Natural Macramé Table Runners (Set of 5)', category: 'Textiles & linens', tags: tags(['macramé','table runner','natural','cotton','boho']), condition: 'Like New', color: 'Natural', quantity: 4, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Five hand-knotted macramé table runners, each 2m × 25cm, in natural cotton. A tactile, textural centrepiece base. Works beautifully with candles, flowers and wooden tableware.' },
      { title: 'Dusty Rose Velvet Napkins (Set of 30)', category: 'Textiles & linens', tags: tags(['napkins','velvet','dusty rose','pink','wedding']), condition: 'Like New', color: 'Pink', quantity: 3, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Thirty dusty rose velvet napkins, 45cm square. Folded into your preferred style or ring-wrapped (ring hire available). Dry-cleaned and steamed between every hire.' },
      { title: 'Hand-Embroidered Tablecloths (Set of 4, 6ft)', category: 'Textiles & linens', tags: tags(['tablecloth','embroidered','linen','6ft','wedding']), condition: 'Good', color: 'White', quantity: 2, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Four white linen tablecloths with hand-embroidered floral borders, sized for 6ft trestle tables. Each cloth is unique and professionally laundered. A beautiful artisanal touch for any wedding table.' },
      { title: 'Organza Chair Sashes (Set of 50)', category: 'Textiles & linens', tags: tags(['chair sash','organza','white','ivory','wedding']), condition: 'Good', color: 'White', quantity: 5, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Fifty white organza chair sashes, 200cm × 18cm. The classic chiavari or banquet chair finish. Tie in a bow, knot or drape. Washed and pressed between each hire. Available in ivory and white.' },
      { title: 'Jute & Hessian Roll (20m × 1m)', category: 'Textiles & linens', tags: tags(['jute','hessian','roll','rustic','table runner']), condition: 'Good', color: 'Natural', quantity: 4, price1Day: 15, price3Day: 38, price7Day: 75, description: '20m × 1m roll of natural jute hessian. Cut to any length as a table runner, aisle runner or decorative layer. The ultimate rustic event textile at a very accessible price.' },
      { title: 'White Ceiling Draping Kit (30m)', category: 'Textiles & linens', tags: tags(['ceiling draping','fabric','white','marquee','canopy']), condition: 'Good', color: 'White', quantity: 2, price1Day: 45, price3Day: 110, price7Day: 220, description: '30m of sheer white polyester voile ceiling draping fabric, with ceiling hooks, clips and cable ties for installation. Transform any ceiling into a romantic billowing canopy. Installation service available.' },
      { title: 'Polyester Tablecloth Bundle (×20, mixed)', category: 'Textiles & linens', tags: tags(['tablecloths','polyester','mixed colours','bulk','event']), condition: 'Good', color: 'Mixed', quantity: 5, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Twenty round or rectangular polyester tablecloths in mixed colours. Available in white, ivory, black, navy and sage. Ideal for large corporate events or multi-table weddings. Pressed before hire.' },
      { title: 'Burnout Velvet Table Overlays (Set of 6)', category: 'Textiles & linens', tags: tags(['velvet','overlay','burnout','table','luxury']), condition: 'Like New', color: 'Gold', quantity: 2, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Six burnout velvet table overlays in antique gold, approx 150cm × 150cm. Draped over standard tablecloths for a luxurious layered look. Sheer-backed velvet with an intricate floral pattern.' },
      { title: 'Satin Chair Sashes (Set of 40, ivory)', category: 'Textiles & linens', tags: tags(['satin','chair sash','ivory','white','wedding']), condition: 'Good', color: 'Neutral', quantity: 6, price1Day: 18, price3Day: 44, price7Day: 88, description: 'Forty ivory satin chair sashes, 200cm × 18cm. A timeless classic for any wedding venue. Dry-cleaned and pressed to a perfect satin sheen between every hire.' },
    ],
  },
  {
    email: 'petra@oddfolk-seed.test', name: 'Petra Kovalenko', username: 'petrak',
    bio: 'Stylist and furniture enthusiast in Stoke Newington. My collection spans mid-century modern to contemporary statement pieces.',
    location: { name: 'Stoke Newington Home', address: '55 Church Street', postcode: 'N16 0AR', city: 'London', lat: 51.5607, lng: -0.0745 },
    listings: [
      { title: 'Acrylic Ghost Dining Table (6-seater)', category: 'Event furniture', tags: tags(['ghost table','acrylic','transparent','modern','6-seater']), condition: 'Like New', color: 'Neutral', quantity: 1, price1Day: 70, price3Day: 170, price7Day: 340, description: 'Stunning all-acrylic ghost dining table that appears to float. 6-seater, 180cm diameter round. An incredible focal point for high-end events, editorial shoots or luxury weddings.' },
      { title: 'Vintage Brass Drinks Trolley', category: 'Vintage & antique', tags: tags(['drinks trolley','brass','bar cart','vintage','gold']), condition: 'Good', color: 'Gold', quantity: 2, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Vintage-style brass drinks trolley on castors. Two shelves for bottles, glasses and garnishes. A beautiful cocktail hour centrepiece or roaming drinks station for intimate events.' },
      { title: 'Rattan Loveseat Sofa', category: 'Soft furnishings', tags: tags(['rattan','loveseat','sofa','two seater','boho']), condition: 'Good', color: 'Natural', quantity: 1, price1Day: 40, price3Day: 95, price7Day: 190, description: 'Rattan two-seater loveseat sofa with cream linen cushions. A charming garden party or bohemian event centrepiece. Works beautifully indoors and in covered outdoor spaces.' },
      { title: 'Bentwood Café Chairs (Set of 8)', category: 'Event furniture', tags: tags(['bentwood','thonet','café chairs','wooden','vintage']), condition: 'Good', color: 'Brown', quantity: 2, price1Day: 35, price3Day: 85, price7Day: 170, description: 'Eight classic Thonet-style bentwood café chairs. Timeless, lightweight and incredibly versatile. The perfect accompanying chair for trestle or farm tables at bistro-themed or vintage events.' },
      { title: 'Industrial Cast Iron Bar Table', category: 'Event furniture', tags: tags(['bar table','cast iron','industrial','high top','poseur']), condition: 'Good', color: 'Black', quantity: 3, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Industrial round cast iron poseur/bar table on a pedestal base, 110cm tall. Heavy and sturdy. Perfect for cocktail receptions and industrial-themed venues. Diameter 60cm — ideal for drinks and nibbles.' },
      { title: 'Velvet Throne Chair (gold frame)', category: 'Event furniture', tags: tags(['throne chair','velvet','gold','statement','wedding']), condition: 'Like New', color: 'Gold', quantity: 2, price1Day: 45, price3Day: 110, price7Day: 220, description: 'Opulent velvet throne chair with carved gold-finish frame and deep seat cushion. Available in blush pink, emerald and navy velvet. The ultimate sweetheart or birthday throne.' },
      { title: 'Reclaimed Oak Cable Drum Table', category: 'Event furniture', tags: tags(['cable drum','table','reclaimed','rustic','oak']), condition: 'Good', color: 'Natural', quantity: 3, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Large reclaimed oak cable drum repurposed as a bar-height drinks or display table. 80cm diameter, 100cm tall. Rough-sanded and sealed. Adds authentic industrial character to any venue.' },
      { title: 'Wicker Egg Chair with Cushion', category: 'Soft furnishings', tags: tags(['egg chair','wicker','rattan','hanging','garden']), condition: 'Like New', color: 'Natural', quantity: 2, price1Day: 35, price3Day: 85, price7Day: 170, description: 'Classic wicker egg chair with a plump cushion insert in ivory or sage linen. Hangs from a steel frame (included) or a beam. A beloved photo moment piece for weddings and garden parties.' },
      { title: 'Hairpin Leg Side Tables (Set of 4)', category: 'Event furniture', tags: tags(['hairpin','side table','mid-century','steel','minimal']), condition: 'Like New', color: 'Natural', quantity: 3, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Four round side tables with hairpin steel legs and an oak veneer top, 45cm diameter. Scatter around a lounge area, use as drink stations or group as a coffee table cluster.' },
      { title: 'Folding Trestle Tables (6ft, Set of 5)', category: 'Event furniture', tags: tags(['trestle table','folding','6ft','lightweight','catering']), condition: 'Good', color: 'White', quantity: 2, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Five lightweight folding trestle tables, 6ft × 2.5ft, in white laminate. Stack flat for easy transport. The essential workhorse table for any event — buffet, gift, welcome or dining.' },
    ],
  },
  {
    email: 'dami@oddfolk-seed.test', name: 'Dami Adeyemi', username: 'damia',
    bio: 'Event decorator based in Bermondsey. I specialise in floral installations, balloon art and statement lighting for memorable celebrations.',
    location: { name: 'Bermondsey Storage', address: '7 Tower Bridge Road', postcode: 'SE1 4TW', city: 'London', lat: 51.4973, lng: -0.0796 },
    listings: [
      { title: 'Maypole Floral Centrepiece Frame', category: 'Props & décor', tags: tags(['maypole','centrepiece','floral','ribbons','wedding']), condition: 'Good', color: 'Gold', quantity: 2, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Elegant maypole centrepiece frame in brushed gold, 180cm tall. Hang ribbons, flowers or trailing greenery for a romantic, movement-filled table centrepiece. Flat-packed for easy transport.' },
      { title: 'Giant Chrome Balloons (Set of 20)', category: 'Props & décor', tags: tags(['balloons','chrome','giant','metallic','party']), condition: 'Like New', color: 'Silver', quantity: 5, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Twenty giant 90cm chrome balloons in silver, gold or rose gold (specify preference). Pre-inflated with helium on the day. Perfect for photo walls, arch fillers or ceiling installations.' },
      { title: 'White Rose Flower Wall (2m × 2m)', category: 'Props & décor', tags: tags(['flower wall','roses','white','backdrop','installation']), condition: 'Good', color: 'White', quantity: 1, price1Day: 85, price3Day: 210, price7Day: 420, description: 'Stunning 2m × 2m artificial white rose flower wall on a modular frame. A timeless, Instagram-ready backdrop for weddings, birthdays and brand activations. Delivery and setup included locally.' },
      { title: 'Powder Blue Velvet Butterfly Chair', category: 'Soft furnishings', tags: tags(['butterfly chair','velvet','blue','retro','chair']), condition: 'Like New', color: 'Blue', quantity: 2, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Iconic powder blue velvet butterfly (papasan) chair with a chrome frame. Retro and playful. Perfect as a photobooth chair, lounge piece or birthday throne for a pastel-themed event.' },
      { title: 'Terrarium Display Table Cluster', category: 'Plants & florals', tags: tags(['terrarium','glass','plants','display','geometric']), condition: 'Like New', color: 'Neutral', quantity: 2, price1Day: 35, price3Day: 85, price7Day: 170, description: 'Six geometric glass terrarium vessels in mixed sizes, styled with preserved moss, ferns and pebbles. Grouped together as a centrepiece cluster they create a beautiful living table display.' },
      { title: 'Dried Flower Petal Runner Set (×5)', category: 'Plants & florals', tags: tags(['petal runner','dried flowers','table','bohemian','natural']), condition: 'Like New', color: 'Mixed', quantity: 3, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Five 2m dried flower petal table runners, each a mix of dried rose petals, lavender, statice and dried leaves. Beautiful scattered loosely along dining tables for a maximalist boho look.' },
      { title: 'Gold Vintage Post Box', category: 'Props & décor', tags: tags(['post box','gold','vintage','cards','wedding']), condition: 'Good', color: 'Gold', quantity: 2, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Charming vintage-style gold post box for collecting wedding cards and gift envelopes. Painted gold with a slot top and padlock. Comes with a personalised tag holder.' },
      { title: 'Pyramid Glass Lanterns (Set of 6, Large)', category: 'Lighting', tags: tags(['lanterns','glass','pyramid','candle','floor']), condition: 'Good', color: 'Neutral', quantity: 2, price1Day: 40, price3Day: 95, price7Day: 190, description: 'Six large pyramid-shaped clear glass lanterns, approx 50cm tall. Stunning clustered on the floor or raised on tables. Use with pillar candles or LED candles for a dramatic effect.' },
      { title: 'Flower Crown Display Stand', category: 'Signage & displays', tags: tags(['flower crown','display','stand','wedding','accessories']), condition: 'Like New', color: 'Gold', quantity: 3, price1Day: 15, price3Day: 38, price7Day: 75, description: 'Elegant gold display stand for flower crowns, headbands or hair accessories. Three-tier rotating design. Perfect for bridesmaids accessories or a floral headband bar at your event.' },
      { title: 'LED Starcloth Backdrop (3m × 3m)', category: 'Lighting', tags: tags(['starcloth','LED','backdrop','twinkle','black']), condition: 'Like New', color: 'Black', quantity: 2, price1Day: 55, price3Day: 135, price7Day: 270, description: 'Black velvet LED starcloth backdrop, 3m × 3m, with 300 individually twinkling warm white LEDs. The classic high-impact event backdrop for photobooth areas, dancefloors and stage settings.' },
    ],
  },
  {
    email: 'luca@oddfolk-seed.test', name: 'Luca Fontaine', username: 'lucaf',
    bio: 'Tropical events specialist in Bow. I offer a unique collection of exotic, botanical and festival-inspired props for unforgettable events.',
    location: { name: 'Bow Studio', address: '88 Roman Road', postcode: 'E3 5ES', city: 'London', lat: 51.5282, lng: -0.0188 },
    listings: [
      { title: 'Moroccan Leather Pouffes (Set of 6)', category: 'Soft furnishings', tags: tags(['pouffe','moroccan','leather','seating','colourful']), condition: 'Good', color: 'Mixed', quantity: 2, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Six authentic Moroccan leather pouffes in vibrant colours — red, orange, teal, purple, yellow and lime. Stuffed firmly. Perfect seating for festival-themed events, Eid celebrations or boho parties.' },
      { title: 'Carved Wooden Room Divider Screen', category: 'Props & décor', tags: tags(['room divider','screen','carved','wooden','moroccan']), condition: 'Good', color: 'Natural', quantity: 2, price1Day: 40, price3Day: 95, price7Day: 190, description: 'Four-panel carved wooden room divider screen, 180cm tall. Intricate Moorish lattice pattern. Use to zone spaces, as a backdrop or to create intimate nooks within larger venues.' },
      { title: 'Rattan Wall Fans (Set of 5, 60cm)', category: 'Props & décor', tags: tags(['rattan fan','wall décor','tropical','boho','display']), condition: 'Like New', color: 'Natural', quantity: 3, price1Day: 15, price3Day: 38, price7Day: 75, description: 'Five large 60cm rattan wall fans in natural tone. Arrange as a feature wall, scatter as table centrepieces or hang from ceiling beams. A beautiful tropical bohemian detail.' },
      { title: 'Copper Hanging Moon Gate Frame (6ft)', category: 'Props & décor', tags: tags(['moon gate','copper','arch','circle','wedding']), condition: 'Like New', color: 'Copper', quantity: 1, price1Day: 45, price3Day: 110, price7Day: 220, description: 'Freestanding 6ft copper circular moon gate arch. The most photogenic ceremony backdrop of the season. Drape with florals, greenery or fabric. Heavy base — safely freestanding on flat surfaces.' },
      { title: 'Tropical Leaf Printed Tablecloths (Set of 6)', category: 'Textiles & linens', tags: tags(['tablecloth','tropical','leaf print','jungle','round']), condition: 'Like New', color: 'Green', quantity: 3, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Six 180cm round tablecloths in a bold tropical leaf print. Instantly transforms any table into an exotic gathering spot. Wrinkle-resistant polyester — steam before use.' },
      { title: 'Hanging Macramé Plant Holders (Set of 8)', category: 'Props & décor', tags: tags(['macramé','plant holder','hanging','bohemian','natural']), condition: 'Good', color: 'Natural', quantity: 3, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Eight hand-knotted macramé plant pot holders in various sizes. Hang from beams, arches or ceiling hooks with small potted plants or succulents inside. A warm, organic decorative detail.' },
      { title: 'Bamboo Tiki Bar Unit', category: 'Event furniture', tags: tags(['tiki bar','bamboo','tropical','bar','events']), condition: 'Good', color: 'Natural', quantity: 1, price1Day: 40, price3Day: 95, price7Day: 190, description: 'Handcrafted bamboo tiki bar unit, 180cm wide × 110cm tall. Complete with a thatch roof canopy and two bamboo bar stools. The centrepiece of any tropical or festival-themed event.' },
      { title: 'Rattan Serving Trays (Set of 6)', category: 'Tableware', tags: tags(['serving tray','rattan','wicker','catering','natural']), condition: 'Good', color: 'Natural', quantity: 3, price1Day: 15, price3Day: 38, price7Day: 75, description: 'Six oval rattan serving trays in two sizes. Beautiful for canapé service, DIY bar setups or styled flat lays. A natural, tactile alternative to plain plastic or metal trays.' },
      { title: 'Silk Hibiscus Lei Garlands (Set of 20)', category: 'Props & décor', tags: tags(['lei','garland','hibiscus','tropical','hawaiian']), condition: 'Like New', color: 'Mixed', quantity: 5, price1Day: 15, price3Day: 38, price7Day: 75, description: 'Twenty colourful silk hibiscus lei garlands for guests. Perfect welcome gifts for tropical, Hawaiian or summer festival-themed events. One size fits all. Machine washable.' },
      { title: 'Tropical Floral Backdrop Stand (2m × 2m)', category: 'Plants & florals', tags: tags(['backdrop','tropical','flowers','stand','2m']), condition: 'Like New', color: 'Green', quantity: 1, price1Day: 40, price3Day: 95, price7Day: 190, description: 'Large 2m × 2m backdrop frame pre-dressed with artificial tropical flowers, palm leaves and hanging greenery. Freestanding on an aluminium frame. No installation needed — arrive, unfold, done.' },
    ],
  },
  {
    email: 'yemi@oddfolk-seed.test', name: 'Yemi Badmus', username: 'yemib',
    bio: 'Party and outdoor events specialist in Walthamstow. I have a great range of games, outdoor furniture and festival-style props for hire.',
    location: { name: 'Walthamstow Garden', address: '12 Hoe Street', postcode: 'E17 4SD', city: 'London', lat: 51.5826, lng: -0.0198 },
    listings: [
      { title: 'Giant Garden Jenga Set (120 pieces)', category: 'Props & décor', tags: tags(['jenga','garden games','giant','outdoor','party']), condition: 'Good', color: 'Natural', quantity: 2, price1Day: 20, price3Day: 48, price7Day: 95, description: '120-piece giant garden Jenga set. Blocks measure 22cm × 7cm × 4cm. Comes in a carry bag. Suitable for outdoor and indoor use. Suitable for all ages — a guest-pleasing activity for any event.' },
      { title: 'Full Croquet Set (6 players)', category: 'Props & décor', tags: tags(['croquet','garden game','outdoor','lawn','6 player']), condition: 'Good', color: 'Mixed', quantity: 2, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Traditional six-player croquet set with mallets, balls, hoops and pegs in a canvas carry bag. Brings a classic English garden party feel to any outdoor event.' },
      { title: 'Giant Connect Four (outdoor)', category: 'Props & décor', tags: tags(['connect four','garden game','giant','outdoor','party']), condition: 'Good', color: 'Natural', quantity: 2, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Giant freestanding Connect Four game, 90cm tall. Includes 42 discs in two colours. A crowd-pleasing activity that encourages mixing at corporate events, garden parties and weddings.' },
      { title: 'Rainbow Bunting & Pennant Flags (30m)', category: 'Signage & displays', tags: tags(['bunting','flags','pennant','outdoor','colourful']), condition: 'Good', color: 'Mixed', quantity: 5, price1Day: 15, price3Day: 38, price7Day: 75, description: '30m of brightly coloured cotton bunting and pennant flags. Strung on natural twine. Instant festival or garden party atmosphere. Available in vintage pastel or rainbow mix.' },
      { title: 'Outdoor Cinema Screen (12ft)', category: 'Audio visual', tags: tags(['cinema screen','outdoor','projection','12ft','film night']), condition: 'Like New', color: 'White', quantity: 1, price1Day: 75, price3Day: 185, price7Day: 370, description: '12ft inflatable outdoor cinema screen with blower pump, projector stand and pegs. Pairs perfectly with our HD projector hire. Perfect for summer screenings, corporate events and private film nights.' },
      { title: 'Festival Hay Bales (Set of 6)', category: 'Event furniture', tags: tags(['hay bales','outdoor','seating','rustic','festival']), condition: 'Good', color: 'Natural', quantity: 2, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Six genuine straw hay bales for outdoor festival seating. Great with a blanket or cushion on top. A rustic seating solution for barn events, outdoor festivals and garden parties.' },
      { title: 'Vintage Milk Churn Vases (Set of 4)', category: 'Props & décor', tags: tags(['milk churn','vase','vintage','rustic','floral']), condition: 'Good', color: 'Silver', quantity: 3, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Four vintage-style galvanised metal milk churns in mixed heights. Fill with wildflowers, sunflowers or foliage for a rustic countryside aesthetic. Also beautiful as empty entrance displays.' },
      { title: 'Wicker Picnic Hamper Set (Set of 4)', category: 'Props & décor', tags: tags(['picnic hamper','wicker','outdoor','garden party','prop']), condition: 'Good', color: 'Natural', quantity: 3, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Four large wicker picnic hampers with leather straps. Styled open with a blanket and food props they create a beautiful boho garden party aesthetic. Also functional for real hamper food service.' },
      { title: 'Wooden Bar Gate & Arch', category: 'Event furniture', tags: tags(['bar','arch','wooden','entrance','gate']), condition: 'Good', color: 'Natural', quantity: 1, price1Day: 35, price3Day: 85, price7Day: 170, description: "6ft wide × 7ft tall wooden arch gate, perfect as a bar entrance, welcome arch or photo opportunity frame. Reclaimed timber construction. Finish with foliage, signage or fairy lights." },
      { title: 'Outdoor Fire Torch Stands (Set of 6)', category: 'Lighting', tags: tags(['fire torch','outdoor','lighting','garden','evening']), condition: 'Good', color: 'Black', quantity: 2, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Six tall outdoor fire torch stands, 150cm tall, with stainless steel bowls. Uses lamp oil (not included). Creates a dramatic boundary lighting effect for evening outdoor events. Safety instructions provided.' },
    ],
  },
  {
    email: 'rosa@oddfolk-seed.test', name: 'Rosa Thorn', username: 'rosat',
    bio: 'Vintage stylist in Streatham with a love for maximalism, shimmer and glamour. My collection is designed for events that deserve a showstopping aesthetic.',
    location: { name: 'Streatham Home', address: '40 Streatham High Road', postcode: 'SW16 1DA', city: 'London', lat: 51.4277, lng: -0.1224 },
    listings: [
      { title: 'Perfume Bottle Centrepieces (Set of 12)', category: 'Props & décor', tags: tags(['perfume bottle','centrepiece','vintage','glamour','table']), condition: 'Like New', color: 'Mixed', quantity: 2, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Twelve oversized vintage-style glass perfume bottles in amber, teal and clear. Fill with coloured water, flowers or fairy lights for a glamorous table centrepiece display.' },
      { title: 'Pearl Bead Curtain Backdrop (2m × 2m)', category: 'Textiles & linens', tags: tags(['pearl curtain','backdrop','beads','glamour','white']), condition: 'Good', color: 'White', quantity: 2, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Lush white pearl bead curtain backdrop, 2m wide × 2m long. Hangs from a curtain pole or tension rod. A romantic, glamorous backdrop for photo areas, cake tables or ceremony archways.' },
      { title: 'Pastel Tassel Garlands (Set of 5, 2m)', category: 'Props & décor', tags: tags(['tassel','garland','pastel','party','colourful']), condition: 'Good', color: 'Mixed', quantity: 4, price1Day: 15, price3Day: 38, price7Day: 75, description: 'Five 2m pastel tassel garlands in coordinating sorbet shades — lemon, blush, mint, lilac and peach. Hang from ceilings, doorways or table edges for a fiesta-inspired celebration aesthetic.' },
      { title: 'Mirrored Disco Ball (45cm)', category: 'Props & décor', tags: tags(['disco ball','mirror','45cm','dance floor','party']), condition: 'Like New', color: 'Silver', quantity: 2, price1Day: 35, price3Day: 85, price7Day: 170, description: 'Large 45cm professional mirrored disco ball on a hanging motor (spins). Pair with spotlights for mesmerising reflections across the whole venue. A dancefloor essential and photogenic statement piece.' },
      { title: 'Iridescent Sequin Tablecloths (Set of 8)', category: 'Textiles & linens', tags: tags(['sequin','tablecloth','iridescent','shimmer','party']), condition: 'Good', color: 'Silver', quantity: 2, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Eight iridescent sequin tablecloths, 180cm round, in mermaid/holographic silver. Utterly dazzling under lighting. Perfect for milestone birthdays, NYE parties or maximalist weddings.' },
      { title: 'Giant Ostrich Feather Fan Display (Set of 3)', category: 'Props & décor', tags: tags(['feather fan','ostrich','display','glamour','burlesque']), condition: 'Good', color: 'White', quantity: 2, price1Day: 40, price3Day: 95, price7Day: 190, description: 'Three enormous white ostrich feather fan displays, each approx 90cm span. Mounted on a weighted display stand. A dramatic, old-Hollywood glamour installation for photobooth corners or entrance halls.' },
      { title: 'Champagne Tower Pyramid Stand (150 glasses)', category: 'Tableware', tags: tags(['champagne tower','pyramid','glasses','wedding','party']), condition: 'Like New', color: 'Gold', quantity: 1, price1Day: 35, price3Day: 85, price7Day: 170, description: 'Gold champagne tower pyramid stand for 150 glasses, pre-stacked to 8 tiers. Includes all 150 champagne flutes. The most spectacular toast moment at any celebration. Setup guide included.' },
      { title: 'White Tulle Table Skirts (Set of 6)', category: 'Textiles & linens', tags: tags(['tulle','table skirt','white','dessert table','wedding']), condition: 'Good', color: 'White', quantity: 3, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Six white tulle table skirts for 6ft or 5ft round tables. Elastic top for easy fitting. Layers of tulle create a cloud-like, princess-worthy effect. Perfect for dessert tables and cake displays.' },
      { title: 'Shell & Pearl Place Card Holders (Set of 30)', category: 'Tableware', tags: tags(['place card holders','shells','pearl','coastal','wedding']), condition: 'Like New', color: 'Neutral', quantity: 3, price1Day: 15, price3Day: 38, price7Day: 75, description: 'Thirty natural shell and faux pearl place card holders. Each shell is unique. Beautiful for coastal-themed weddings, beach parties or any event with a romantic, natural aesthetic.' },
      { title: 'Glitter Balloon Cloud Kit', category: 'Props & décor', tags: tags(['balloons','cloud','installation','glitter','ceiling']), condition: 'Good', color: 'Mixed', quantity: 2, price1Day: 45, price3Day: 110, price7Day: 220, description: 'Everything needed to create a dreamy ceiling balloon cloud installation — 50 mixed pastel balloons, clear fishing line, command hooks and iridescent tissue paper. Setup instructions included.' },
    ],
  },
  {
    email: 'callum@oddfolk-seed.test', name: 'Callum Stewart', username: 'callums',
    bio: 'Set builder and events carpenter in Lewisham. I build and hire out industrial and bespoke furniture with a raw, handcrafted aesthetic.',
    location: { name: 'Lewisham Workshop', address: '5 Lee High Road', postcode: 'SE13 5LD', city: 'London', lat: 51.4615, lng: -0.0118 },
    listings: [
      { title: 'Scaffold Board Bar Unit (3m)', category: 'Event furniture', tags: tags(['bar','scaffold','industrial','bespoke','catering']), condition: 'Good', color: 'Natural', quantity: 1, price1Day: 60, price3Day: 145, price7Day: 290, description: 'Handbuilt 3m bar unit in reclaimed scaffold boards on a black steel pipe frame. Shelf behind bar and bottle hooks included. The definitive industrial bar statement for warehouse or outdoor events.' },
      { title: 'Pallet Sofa Set (sofa + 2 armchairs)', category: 'Event furniture', tags: tags(['pallets','sofa','outdoor','industrial','seating']), condition: 'Good', color: 'Natural', quantity: 1, price1Day: 40, price3Day: 95, price7Day: 190, description: 'Handbuilt pallet furniture set — one two-seater sofa and two matching armchairs — with cream or charcoal cushions. Rugged yet comfortable. Perfect for outdoor festival or industrial venue lounge areas.' },
      { title: 'Copper Pipe Shelving Display Unit', category: 'Signage & displays', tags: tags(['shelving','copper pipe','industrial','display','retail']), condition: 'Good', color: 'Copper', quantity: 2, price1Day: 35, price3Day: 85, price7Day: 170, description: 'Freestanding copper pipe and reclaimed wood shelving unit, 150cm tall × 100cm wide. Three shelves. Beautiful as a dessert display, bar back unit or decoration display at weddings and pop-ups.' },
      { title: 'Large Chalkboard Wall Panel (6ft × 3ft)', category: 'Signage & displays', tags: tags(['chalkboard','wall panel','large','signage','menu']), condition: 'Good', color: 'Black', quantity: 2, price1Day: 25, price3Day: 60, price7Day: 120, description: "Oversized 6ft × 3ft freestanding chalkboard panel. A huge canvas for your artist to create menus, seating plans or welcome art. Chalk pens and chalk sticks included. Easel back for freestanding use." },
      { title: 'Industrial Drum Seat Set (Set of 4)', category: 'Event furniture', tags: tags(['drum stool','industrial','metal','bar stool','seating']), condition: 'Good', color: 'Black', quantity: 3, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Four painted steel industrial drum stools with welded seating rings. Raw, utilitarian and surprisingly comfortable. Bar height at 65cm. Great for industrial-themed events or as bar stools.' },
      { title: 'Whisky Barrel Side Tables (Set of 4)', category: 'Event furniture', tags: tags(['whisky barrel','table','rustic','wooden','industrial']), condition: 'Good', color: 'Brown', quantity: 2, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Four genuine whisky barrel halves repurposed as side tables or poseur tables. 55cm diameter, 50cm tall. Character-filled — each with original barrel markings, bands and wood grain.' },
      { title: 'Beer Keg Bar Conversion Unit', category: 'Event furniture', tags: tags(['beer keg','bar','drinks table','industrial','upcycled']), condition: 'Good', color: 'Silver', quantity: 2, price1Day: 40, price3Day: 95, price7Day: 190, description: 'Polished stainless steel beer keg converted into a 110cm tall drinks table. Top surface is flat and stable. A great talking point as a bar poseur table or drinks station at any event.' },
      { title: 'Edison Bulb Letter Signs (A–Z, 30cm)', category: 'Signage & displays', tags: tags(['letter signs','Edison','light up','alphabet','signage']), condition: 'Good', color: 'Natural', quantity: 1, price1Day: 15, price3Day: 38, price7Day: 75, description: 'Full alphabet set of 30cm wooden-backed Edison bulb letters. Each letter plugs into standard 13A sockets via a standard flex. Hire individual letters at £5/letter/day or take the full set.' },
      { title: 'Metal Mesh Ceiling Grid (5m × 3m)', category: 'Props & décor', tags: tags(['ceiling grid','mesh','industrial','hanging','installation']), condition: 'Good', color: 'Black', quantity: 1, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Black powder-coated wire mesh ceiling installation grid, 5m × 3m. Hang from venue ceiling hooks. Dress with lights, greenery, flowers or fabric drops. The foundation for extraordinary ceiling installs.' },
      { title: 'Concrete Planters (Set of 4, XL)', category: 'Plants & florals', tags: tags(['planter','concrete','modern','outdoor','garden']), condition: 'Like New', color: 'Neutral', quantity: 2, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Four XL lightweight concrete-effect planters, 40cm diameter × 40cm tall. Modern and minimal. Pair with olive trees, agave or large-leafed tropicals for a contemporary venue entrance.' },
    ],
  },
  {
    email: 'nadia@oddfolk-seed.test', name: 'Nadia Hussain', username: 'nadiah',
    bio: 'Moroccan and South Asian event specialist based in Woolwich. I curate an exceptional collection of textiles, lanterns and props for culturally-rich celebrations.',
    location: { name: 'Woolwich Home', address: '9 Powis Street', postcode: 'SE18 6LQ', city: 'London', lat: 51.4897, lng: 0.0656 },
    listings: [
      { title: 'Moroccan Canopy & Draping Kit', category: 'Textiles & linens', tags: tags(['canopy','moroccan','draping','tent','colourful']), condition: 'Good', color: 'Mixed', quantity: 1, price1Day: 55, price3Day: 135, price7Day: 270, description: 'Full Moroccan-style canopy kit: 30m of multicoloured silk draping fabric, ceiling hooks, a central chandelier mounting point and decorative tassels. Transforms any room into an Arabian nights scene.' },
      { title: 'Boho Tipi (6ft, white canvas)', category: 'Props & décor', tags: tags(['tipi','teepee','boho','white','canvas']), condition: 'Good', color: 'White', quantity: 2, price1Day: 45, price3Day: 110, price7Day: 220, description: '6ft tall white canvas boho tipi. Perfect as a children\'s play zone, a quiet garden retreat or a ceremony backdrop. Poles and pegs included. Suitable for indoor and outdoor use on flat ground.' },
      { title: 'Kilim Runner Rugs (Set of 3)', category: 'Soft furnishings', tags: tags(['kilim','rug','runner','persian','colourful']), condition: 'Good', color: 'Mixed', quantity: 3, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Three genuine Turkish kilim flat-weave runner rugs in rich geometric patterns. Each approx 250cm × 80cm. Beautiful layered along ceremony aisles or lounge areas for an eclectic, world-inspired aesthetic.' },
      { title: 'Brass Moroccan Tea Set', category: 'Tableware', tags: tags(['moroccan','tea set','brass','tea glasses','arabic']), condition: 'Good', color: 'Gold', quantity: 3, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Authentic Moroccan brass teapot and eight glass tea cups on a hammered copper tray. Beautiful for Mehndi nights, Arabic-themed weddings or any event with a Middle Eastern influence.' },
      { title: 'Rattan Camel Stools (Set of 4)', category: 'Event furniture', tags: tags(['camel stool','rattan','moroccan','low seating','boho']), condition: 'Good', color: 'Natural', quantity: 4, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Four carved rattan and carved wood camel-motif stools, 45cm tall. Beautiful as low seating around floor-level tables or as side table alternatives in a Moroccan lounge setup.' },
      { title: 'Woven Grass Wall Mat (2m × 3m)', category: 'Props & décor', tags: tags(['grass mat','wall hanging','natural','texture','backdrop']), condition: 'Good', color: 'Natural', quantity: 2, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Large 2m × 3m handwoven seagrass wall mat. Hangs from a wooden rod (included). A stunning natural textured backdrop for bohemian ceremonies, photoshoots and wellness events.' },
      { title: 'Hammered Copper Serving Bowls (Set of 6)', category: 'Tableware', tags: tags(['copper','serving bowls','hammered','mezze','catering']), condition: 'Good', color: 'Copper', quantity: 3, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Six hammered copper serving bowls in three sizes. Perfect for mezze spreads, Indian sharing platters or wedding feast catering displays. Beautiful, tactile and warm in any lighting.' },
      { title: 'Embroidered Tent Divider Curtains (Set of 4)', category: 'Textiles & linens', tags: tags(['curtains','embroidered','divider','tent','colourful']), condition: 'Good', color: 'Mixed', quantity: 2, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Four heavily embroidered sheer divider curtains in vibrant jewel tones with mirror work detailing. Each panel 250cm × 120cm. Create intimate zones within a large venue or marquee.' },
      { title: 'Oil Lantern Pillar Cluster (Set of 8)', category: 'Lighting', tags: tags(['lantern','oil lamp','pillar','moroccan','atmospheric']), condition: 'Good', color: 'Copper', quantity: 2, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Eight varying-height copper and brass oil pillar lanterns. Uses lamp oil (not included). Arranged in a cluster they create a dramatic, atmospheric lighting installation perfect for Mehndi nights or garden events.' },
      { title: 'Sand Ceremony Bottle Set', category: 'Props & décor', tags: tags(['sand ceremony','wedding','unity ceremony','bottles','personalised']), condition: 'Like New', color: 'Neutral', quantity: 5, price1Day: 15, price3Day: 38, price7Day: 75, description: 'Sand ceremony set: one large display vessel and two smaller pouring bottles with coloured sand (choice of 12 colours). A meaningful unity ceremony alternative. Personalised label included.' },
    ],
  },
  {
    email: 'eli@oddfolk-seed.test', name: 'Eli Vance', username: 'eliv',
    bio: 'Retro pop culture enthusiast and event stylist in Hammersmith. My collection spans 1950s diners to 1970s discos for immersive themed events.',
    location: { name: 'Hammersmith Studio', address: '25 King Street', postcode: 'W6 9JT', city: 'London', lat: 51.4920, lng: -0.2228 },
    listings: [
      { title: 'Mid-Century Danish Sideboard', category: 'Vintage & antique', tags: tags(['sideboard','danish','mid-century','teak','furniture']), condition: 'Good', color: 'Brown', quantity: 1, price1Day: 50, price3Day: 120, price7Day: 240, description: 'Genuine 1960s Danish teak sideboard with sliding doors and tapered legs. Approx 160cm wide. A beautiful serving or display surface for wedding breakfasts, events and editorial shoots.' },
      { title: 'Tulip Pedestal Dining Table (white)', category: 'Event furniture', tags: tags(['tulip table','pedestal','white','round','Saarinen']), condition: 'Good', color: 'White', quantity: 1, price1Day: 45, price3Day: 110, price7Day: 220, description: 'Saarinen-inspired Tulip pedestal dining table in white fibreglass and marble-effect top. 120cm diameter. An iconic piece of design history. Pairs beautifully with any seating style.' },
      { title: 'Eames-Style Fibreglass Armchairs (Set of 4)', category: 'Event furniture', tags: tags(['Eames','fibreglass','armchair','retro','colourful']), condition: 'Good', color: 'Mixed', quantity: 2, price1Day: 50, price3Day: 120, price7Day: 240, description: 'Four Eames DAR-style fibreglass shell armchairs in assorted colours — orange, yellow, blue and red — on black Eiffel wire bases. Iconic, retro and endlessly photogenic.' },
      { title: 'Retro Stacking Chairs (Set of 10, mixed)', category: 'Event furniture', tags: tags(['stacking chairs','retro','colourful','plastic','1970s']), condition: 'Good', color: 'Mixed', quantity: 2, price1Day: 35, price3Day: 85, price7Day: 170, description: "Ten retro solid-colour plastic stacking chairs in a mix of 1970s shades — mustard, orange, avocado and brown. Lightweight, stackable and wonderfully evocative of a different era." },
      { title: 'Lava Lamp Collection (Set of 6)', category: 'Lighting', tags: tags(['lava lamp','retro','60s','70s','ambient']), condition: 'Good', color: 'Mixed', quantity: 2, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Six working lava lamps in assorted retro colourways — red/yellow, blue/white, orange/clear and purple/silver. Plug-and-play, warm up in 30 minutes. Perfect for retro parties and themed events.' },
      { title: 'Polaroid Memories Wall (100 clips + lights)', category: 'Props & décor', tags: tags(['polaroid','photo wall','display','memories','wedding']), condition: 'Like New', color: 'Natural', quantity: 2, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Polaroid-style memory wall kit: 5m of fairy light string with 100 mini wooden clip pegs. Hang guests\' photos, messages or Instax prints. Comes with a welcome note and kraft paper cards.' },
      { title: 'Space Hopper Set (Set of 6)', category: 'Props & décor', tags: tags(['space hopper','retro','children','party','games']), condition: 'Good', color: 'Mixed', quantity: 2, price1Day: 20, price3Day: 48, price7Day: 95, description: "Six inflated vintage-style space hoppers in mixed bright colours. Nostalgic fun for children's parties, retro corporate events or any occasion that needs some carefree, bouncy energy." },
      { title: 'Giant Retro Boombox Prop (80cm)', category: 'Props & décor', tags: tags(['boombox','prop','retro','80s','music']), condition: 'Good', color: 'Black', quantity: 1, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Oversized 80cm fibreglass boombox prop in classic black with chrome details. Realistic-looking prop that photographs brilliantly. A must-have for 80s-themed parties and music-inspired events.' },
      { title: 'Clear Acrylic Bubble Chair', category: 'Soft furnishings', tags: tags(['bubble chair','acrylic','clear','hanging','60s']), condition: 'Like New', color: 'Neutral', quantity: 1, price1Day: 40, price3Day: 95, price7Day: 190, description: 'Iconic Aarnio-inspired clear acrylic bubble chair on a chrome hanging frame. Cushioned interior in cream bouclé. Hangs from the frame — no ceiling attachment needed. A genuine mid-century icon.' },
      { title: 'Vintage Jukebox (working, Bluetooth)', category: 'Audio visual', tags: tags(['jukebox','vintage','music','retro','1950s']), condition: 'Good', color: 'Mixed', quantity: 1, price1Day: 65, price3Day: 160, price7Day: 320, description: 'Beautifully restored vintage-style jukebox with working lighting, Bluetooth streaming and original 45rpm disc display. The centrepiece for any 1950s diner, Grease party or retro-themed event.' },
    ],
  },
  {
    email: 'zara@oddfolk-seed.test', name: 'Zara Mensah', username: 'zaram',
    bio: 'London-themed events specialist in Finsbury Park. I celebrate everything iconic about this city — perfect for weddings and events with a Great British twist.',
    location: { name: 'Finsbury Park Studio', address: '17 Stroud Green Road', postcode: 'N4 3EF', city: 'London', lat: 51.5643, lng: -0.1066 },
    listings: [
      { title: "Neon 'Eat Drink & Be Married' Sign", category: 'Lighting', tags: tags(['neon','sign','wedding','LED','eat drink']), condition: 'Like New', color: 'White', quantity: 1, price1Day: 50, price3Day: 120, price7Day: 240, description: "Hand-bent warm white LED neon 'Eat, Drink & Be Married' sign, 120cm wide. USB powered with 3m cable. Comes with wall mounts and a tabletop acrylic stand. A wedding dinner staple." },
      { title: 'Spinning Glitter Globe Centrepieces (Set of 8)', category: 'Props & décor', tags: tags(['glitter globe','centrepiece','spinning','glamour','table']), condition: 'Good', color: 'Silver', quantity: 2, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Eight battery-powered spinning glitter globes, 20cm tall. Catch any light source and scatter magical reflections across your table. Wind them up and watch the magic happen.' },
      { title: "Giant Champagne Bottle Prop (1m)", category: 'Props & décor', tags: tags(['champagne bottle','prop','giant','celebration','display']), condition: 'Good', color: 'Gold', quantity: 2, price1Day: 25, price3Day: 60, price7Day: 120, description: "1m tall fibreglass champagne bottle prop in gold and black. A dramatic entrance or dancefloor statement for New Year's Eve, birthdays and weddings. Lightweight and freestanding." },
      { title: 'Red Telephone Box Prop (full-size)', category: 'Props & décor', tags: tags(['telephone box','red','London','prop','photo booth']), condition: 'Good', color: 'Red', quantity: 1, price1Day: 50, price3Day: 120, price7Day: 240, description: 'Full-size replica British red telephone box in painted wood. An unmistakable London icon. Perfect for photo opportunities, directional signage or as a vintage drinks cabinet. Local delivery only.' },
      { title: 'Double Decker Bus Model Centrepiece', category: 'Props & décor', tags: tags(['bus','double decker','london','model','centrepiece']), condition: 'Like New', color: 'Red', quantity: 4, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Large 60cm handpainted wooden model of a classic London Routemaster double decker bus. Beautiful table centrepiece for London-themed events. Can hold flowers in the open top deck.' },
      { title: 'Black Cab Photo Booth Prop', category: 'Props & décor', tags: tags(['black cab','taxi','london','prop','photo booth']), condition: 'Good', color: 'Black', quantity: 1, price1Day: 55, price3Day: 135, price7Day: 270, description: 'Half-size replica black London taxi cab front section, on wheels. Opens as a photo opportunity prop. Guests can sit inside for photos. Built in powder-coated steel with an illuminated TAXI sign.' },
      { title: 'Illustrated London Map Backdrop (2m × 1.5m)', category: 'Signage & displays', tags: tags(['map','london','backdrop','illustrated','print']), condition: 'Like New', color: 'Neutral', quantity: 2, price1Day: 35, price3Day: 85, price7Day: 170, description: 'Large 2m × 1.5m fine art giclée print of an illustrated London map on a pull-up banner frame. Beautiful as a welcome display at London-themed events or as a photobooth backdrop.' },
      { title: "'Mr & Mrs' Neon Sign (80cm)", category: 'Lighting', tags: tags(['neon','Mr and Mrs','sign','wedding','LED']), condition: 'Like New', color: 'Pink', quantity: 2, price1Day: 40, price3Day: 95, price7Day: 190, description: "Pink LED neon 'Mr & Mrs' script sign, 80cm wide. USB powered with a tabletop acrylic stand and wall mounting kit. A sweet and photogenic addition to any wedding reception top table." },
      { title: 'Silver Glitter Tree Centrepieces (Set of 4, 5ft)', category: 'Props & décor', tags: tags(['tree','silver','glitter','centrepiece','tall']), condition: 'Good', color: 'Silver', quantity: 2, price1Day: 40, price3Day: 95, price7Day: 190, description: 'Four 5ft silver glitter branch tree centrepieces in weighted metal bases. Hang crystals, ornaments or fairy lights. Spectacular flanking a top table or lining an aisle.' },
      { title: 'Acrylic Podium & Lectern', category: 'Signage & displays', tags: tags(['podium','lectern','acrylic','speeches','clear']), condition: 'Like New', color: 'Neutral', quantity: 2, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Clear acrylic floor-standing podium and lectern with adjustable shelf and microphone holder. The modern transparent speaker\'s lectern. Clean and minimal for speeches, ceremonies and presentations.' },
    ],
  },
  {
    email: 'otto@oddfolk-seed.test', name: 'Otto Berger', username: 'ottob',
    bio: 'Landscape designer and garden event specialist in Borough. My collection covers everything you need for beautiful outdoor events and al fresco dining.',
    location: { name: 'Borough Market Area', address: '33 Borough High Street', postcode: 'SE1 1JX', city: 'London', lat: 51.5006, lng: -0.0903 },
    listings: [
      { title: 'Beer Garden Bench & Table Sets (Set of 5)', category: 'Event furniture', tags: tags(['picnic table','beer garden','outdoor','bench','wooden']), condition: 'Good', color: 'Natural', quantity: 2, price1Day: 45, price3Day: 110, price7Day: 220, description: 'Five matching pine beer garden picnic bench and table sets, each 180cm long. Seats 6–8 guests. Perfect for outdoor summer parties, garden receptions and street food events.' },
      { title: 'Market Garden Umbrellas (Set of 4, 3m, cream)', category: 'Event furniture', tags: tags(['umbrella','parasol','cream','3m','outdoor']), condition: 'Good', color: 'White', quantity: 2, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Four 3m diameter cream canvas market garden umbrellas on weighted bases. Block direct sun and add a Provençal touch to outdoor dining. Frames are powder-coated black. Weighted bases included.' },
      { title: 'Outdoor Rattan Daybed with Canopy', category: 'Soft furnishings', tags: tags(['daybed','rattan','canopy','outdoor','garden']), condition: 'Like New', color: 'Natural', quantity: 1, price1Day: 50, price3Day: 120, price7Day: 240, description: 'Luxurious outdoor rattan daybed with adjustable canopy and cream cushioned mattress. A spectacular focal point for garden events, photography and luxury outdoor entertaining.' },
      { title: 'Wrought Iron Bistro Set (table + 2 chairs)', category: 'Event furniture', tags: tags(['bistro','wrought iron','table','chairs','french']), condition: 'Good', color: 'Black', quantity: 4, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Classic French wrought iron bistro set — small circular table and two matching folding chairs in black. The perfect Parisian café corner for garden parties, engagement shoots and al fresco events.' },
      { title: 'Hanging Rattan Egg Chair', category: 'Soft furnishings', tags: tags(['egg chair','rattan','hanging','garden','outdoor']), condition: 'Good', color: 'Natural', quantity: 2, price1Day: 35, price3Day: 85, price7Day: 170, description: 'Classic hanging rattan egg chair on a freestanding chrome frame. Cream canvas cushion. Beloved garden party prop that guests queue to sit in. Frame folds for easy transport.' },
      { title: 'Garden Arches with Trellis (Pair)', category: 'Props & décor', tags: tags(['garden arch','trellis','climbing plants','outdoor','wooden']), condition: 'Good', color: 'White', quantity: 2, price1Day: 25, price3Day: 60, price7Day: 120, description: 'Pair of white-painted wooden garden arches with integrated trellis panels, 200cm tall × 100cm wide. Dress with climbing plants, faux florals or ribbon. Perfect flanking an outdoor ceremony aisle.' },
      { title: 'Teak Garden Planter Boxes (Set of 4, long)', category: 'Plants & florals', tags: tags(['planter','teak','garden','outdoor','box']), condition: 'Good', color: 'Brown', quantity: 3, price1Day: 20, price3Day: 48, price7Day: 95, description: 'Four 100cm long teak garden planter boxes on legs, 80cm tall. Pre-drilled drainage holes. Perfect for defining event spaces with topiary, herbs or seasonal planting. Clean, architectural and elegant.' },
      { title: 'Festoon Light Tree Stand (6ft)', category: 'Lighting', tags: tags(['festoon lights','tree','outdoor','garden','evening']), condition: 'Like New', color: 'Natural', quantity: 3, price1Day: 40, price3Day: 95, price7Day: 190, description: 'Six-foot freestanding festoon light tree — a steel branch structure dressed with warm white Edison bulbs. A magical outdoor lighting centrepiece that needs no installation. Plug and play.' },
      { title: 'Outdoor Bar Stools (Set of 6, wooden)', category: 'Event furniture', tags: tags(['bar stools','outdoor','wooden','garden','seating']), condition: 'Good', color: 'Natural', quantity: 3, price1Day: 30, price3Day: 72, price7Day: 145, description: 'Six solid FSC-certified wooden outdoor bar stools with rounded seats and footrests, 65cm tall. Weather-resistant teak oil finish. Perfect for outdoor bars, festival events and garden parties.' },
      { title: 'Cast Iron Fire Pit Bowl (large)', category: 'Props & décor', tags: tags(['fire pit','cast iron','outdoor','evening','autumn']), condition: 'Good', color: 'Black', quantity: 2, price1Day: 35, price3Day: 85, price7Day: 170, description: 'Large 60cm diameter cast iron fire pit bowl on a tripod stand, 80cm tall. Burns logs or charcoal. Creates warmth and atmosphere for autumn and winter outdoor events. Safety gloves and ash pan included.' },
    ],
  },
];

async function main() {
  console.log('Cleaning up existing seed data…');
  const seedEmails = USERS.map(u => u.email);
  const existing = await prisma.user.findMany({ where: { email: { in: seedEmails } }, select: { id: true } });
  const ids = existing.map(u => u.id);
  if (ids.length > 0) {
    await prisma.product.deleteMany({ where: { ownerId: { in: ids } } });
    await prisma.location.deleteMany({ where: { userId: { in: ids } } });
    await prisma.user.deleteMany({ where: { id: { in: ids } } });
  }

  console.log('Seeding users, locations and listings…');
  let productCount = 0;

  for (const userData of USERS) {
    const userId = randomUUID();

    await prisma.user.create({
      data: {
        id: userId,
        email: userData.email,
        name: userData.name,
        username: userData.username,
        bio: userData.bio,
        avatarUrl: `https://i.pravatar.cc/300?u=${userData.email}`,
        emailVerified: true,
      },
    });

    const location = await prisma.location.create({
      data: {
        userId,
        name: userData.location.name,
        address: userData.location.address,
        postcode: userData.location.postcode,
        city: userData.location.city,
        lat: userData.location.lat,
        lng: userData.location.lng,
        type: 'OTHER',
      },
    });

    for (const listing of userData.listings) {
      const slug = listing.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40);
      await prisma.product.create({
        data: {
          ownerId: userId,
          locationId: location.id,
          title: listing.title,
          description: listing.description,
          category: listing.category,
          tags: listing.tags,
          condition: listing.condition,
          color: listing.color,
          quantity: listing.quantity,
          price1Day: listing.price1Day,
          price3Day: listing.price3Day ?? null,
          price7Day: listing.price7Day ?? null,
          images: imgs(slug),
          status: 'ACTIVE',
        },
      });
      productCount++;
    }
  }

  console.log(`✓ Seeded ${USERS.length} users, ${USERS.length} locations, ${productCount} products`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
